package club.skidware.kconfig.error

/**
 * Sealed hierarchy representing all configuration errors that can occur during
 * deserialization, validation, and key resolution.
 *
 * Each subclass captures a specific category of error along with contextual information
 * (path, raw value, expectation) that enables precise diagnostic messages. Errors are
 * accumulated by [ConfigErrorCollector] and rendered by [ConfigErrorFormatter].
 *
 * Example of inspecting errors by type:
 * ```kotlin
 * val errors: List<ConfigError> = collector.all()
 * errors.forEach { error ->
 *     when (error) {
 *         is ConfigError.InvalidValue    -> println("Bad value at ${error.path}")
 *         is ConfigError.UnknownKey      -> println("Typo? ${error.suggestion}")
 *         is ConfigError.OutOfRange      -> println("${error.raw} not in [${error.min}, ${error.max}]")
 *         is ConfigError.PatternMismatch -> println("Regex failed at ${error.path}")
 *         is ConfigError.MissingRequired -> println("Missing: ${error.path}")
 *         is ConfigError.UnknownType     -> println("No serializer for ${error.typeName}")
 *     }
 * }
 * ```
 *
 * @param path Dot-separated path to the offending field (e.g. `"database.port"`).
 * @param message Human-readable description of the error, auto-generated by each subclass.
 * @see ConfigErrorCollector
 * @see ConfigErrorFormatter
 * @since 1.0
 */
sealed class ConfigError(val path: String, val message: String) {

    /**
     * A value was present but could not be converted to the expected type.
     *
     * Generated by [Deserializer][club.skidware.kconfig.reader.Deserializer] when a YAML value
     * (or environment variable string) cannot be coerced to the target Kotlin type, or when an
     * enum constant is not recognised.
     *
     * Example - a non-numeric string where an `Int` is expected:
     * ```yaml
     * port: "not_a_number"
     * ```
     * produces: `InvalidValue(path = "server.port", raw = "not_a_number", expected = "Int")`
     *
     * @param path Dot-separated field path.
     * @param raw The original value from the YAML map (may be `null`).
     * @param expected Human-readable description of the expected type or value set.
     * @param hint Optional contextual hint (e.g. "did you mean 'INFO'?").
     * @since 1.0
     */
    class InvalidValue(path: String, val raw: Any?, val expected: String, val hint: String? = null)
        : ConfigError(path, "Invalid value ${formatRaw(raw)}, expected $expected${hint?.let { " ($it)" } ?: ""}")

    /**
     * No serializer is registered for the requested type.
     *
     * Generated when the [Deserializer][club.skidware.kconfig.reader.Deserializer] encounters a
     * type that is neither a built-in primitive, collection, enum, data class, nor registered in
     * the [SerializerRegistry][club.skidware.kconfig.serializer.SerializerRegistry].
     *
     * Example - a field of type `java.time.Instant` without a custom serializer:
     * ```
     * UnknownType(path = "server.startedAt", typeName = "Instant")
     * ```
     *
     * @param path Dot-separated field path.
     * @param typeName Simple name of the unresolvable type.
     * @param rawSection The raw YAML sub-map, if available, for diagnostics.
     * @since 1.0
     */
    class UnknownType(path: String, val typeName: String, val rawSection: Map<String, Any?>? = null)
        : ConfigError(path, "Unknown type '$typeName' - no serializer registered")

    /**
     * A key in the YAML map does not correspond to any constructor parameter of the target data class.
     *
     * Generated during unknown-key detection in [Deserializer][club.skidware.kconfig.reader.Deserializer].
     * When a close match is found via [Levenshtein distance][closestMatch], it is included as a suggestion.
     *
     * Example - a typo in the YAML file:
     * ```yaml
     * databse:   # should be "database"
     *   host: localhost
     * ```
     * produces: `UnknownKey(path = "databse", suggestion = "database")`
     *
     * @param path Dot-separated field path of the unrecognised key.
     * @param suggestion Closest valid key name, or `null` if no match is within the distance threshold.
     * @see closestMatch
     * @since 1.0
     */
    class UnknownKey(path: String, val suggestion: String? = null)
        : ConfigError(path, "Unknown key '${path.substringAfterLast('.')}'${suggestion?.let { " - did you mean '$it'?" } ?: ""}")

    /**
     * A numeric value violates the bounds declared by the [@Range][club.skidware.kconfig.annotation.Range] annotation.
     *
     * Generated during post-deserialization validation. When the parameter has a Kotlin default
     * value, the deserializer falls back to that default and records the fallback in [fellBackTo].
     *
     * Example:
     * ```kotlin
     * data class Server(@Range(min = 1.0, max = 65535.0) val port: Int = 8080)
     * ```
     * With YAML `port: 99999`:
     * ```
     * OutOfRange(path = "server.port", raw = 99999, min = 1.0, max = 65535.0, fellBackTo = 8080)
     * ```
     *
     * @param path Dot-separated field path.
     * @param raw The numeric value that was out of range.
     * @param min Lower bound (inclusive).
     * @param max Upper bound (inclusive).
     * @param fellBackTo The default value used as a fallback, or `null` if no fallback was available.
     * @since 1.0
     */
    class OutOfRange(path: String, val raw: Number, val min: Double, val max: Double, val fellBackTo: Any? = null)
        : ConfigError(path, "Value $raw is out of range [$min, $max]${fellBackTo?.let { ", fell back to $it" } ?: ""}")

    /**
     * A string value does not match the regex declared by the [@Pattern][club.skidware.kconfig.annotation.Pattern] annotation.
     *
     * Generated during post-deserialization validation. Like [OutOfRange], the deserializer falls
     * back to the Kotlin default when one is available.
     *
     * Example:
     * ```kotlin
     * data class Network(@Pattern(regex = "^(https?://).+") val endpoint: String = "http://localhost")
     * ```
     * With YAML `endpoint: "ftp://files"`:
     * ```
     * PatternMismatch(path = "network.endpoint", raw = "ftp://files", pattern = "^(https?://).+")
     * ```
     *
     * @param path Dot-separated field path.
     * @param raw The string value that failed validation.
     * @param pattern The regex pattern that was expected to match.
     * @param description Optional human-readable description from the annotation.
     * @since 1.0
     */
    class PatternMismatch(path: String, val raw: String, val pattern: String, val description: String? = null)
        : ConfigError(path, "Value '$raw' does not match pattern '$pattern'${description?.let { " ($it)" } ?: ""}")

    /**
     * A required field (non-nullable, no default) is missing from the YAML map.
     *
     * Generated when the YAML map contains no entry for a constructor parameter that is neither
     * optional (has a Kotlin default) nor nullable, and no [@MigrateFrom][club.skidware.kconfig.annotation.MigrateFrom]
     * fallback key resolves to a value.
     *
     * Example:
     * ```kotlin
     * data class Database(val host: String)  // no default, not nullable
     * ```
     * With an empty YAML map:
     * ```
     * MissingRequired(path = "database.host", expected = "String")
     * ```
     *
     * @param path Dot-separated field path.
     * @param expected Human-readable name of the expected type.
     * @since 1.0
     */
    class MissingRequired(path: String, val expected: String)
        : ConfigError(path, "Missing required field, expected $expected")

    /**
     * Companion providing shared formatting utilities for error message construction.
     */
    companion object {
        /**
         * Formats a raw YAML value for inclusion in error messages.
         *
         * Strings are single-quoted, `null` is rendered as the literal `"null"`,
         * and all other types use [Any.toString].
         *
         * @param raw The value to format.
         * @return A display-safe string representation.
         */
        private fun formatRaw(raw: Any?): String = when (raw) {
            null -> "null"
            is String -> "'$raw'"
            else -> raw.toString()
        }
    }
}
